<?php
/**
 * SETUP PAGE
 * ------------------------------------
 * *instructions*
 */


/**
 * Now put the information you gathered here.
 */

// username
$MySQL_Username = "default";

// password
$MySQL_Password = "default";

// database name
$MySQL_Name = "default";

// database host
$MySQL_Host = "default";



/**
 * Advanced Users Only!
 * ----------------------------
 * EDIT AT YOUR OWN RISK!
 */

// Do not touch
$_CW = array();

// default is 'default' (server timezone)
$_CW['settings']['timezone'] = 'default';

// default is 1
$_CW['debug_level'] = 1;

// default is 'default'
$_CW['path'] = 'default';

// default is TRUE
$_CW['settings']['php_error_handler'] = TRUE;

/**
 * Security Keys
 * ----------------
 * Automatically generated by default.
 * Set to 'default' to auto generate.
 */
$_CW['secure']['keys']['auth']              = 'default';
$_CW['secure']['keys']['auth_salt']         = 'default';
$_CW['secure']['keys']['secured_auth']      = 'default';
$_CW['secure']['keys']['secured_auth_salt'] = 'default';
$_CW['secure']['keys']['logged_in']         = 'default';
$_CW['secure']['keys']['logged_in_salt']    = 'default';
$_CW['secure']['keys']['nonce']             = 'default';
$_CW['secure']['keys']['nonce_salt']        = 'default';
$_CW['secure']['keys']['captcha_public']    = 'default';
$_CW['secure']['keys']['captcha_private']   = 'default';



/*------------------------*\
 *      !!!STOP!!!        *
 *                        *
 * Do not edit this file  *
 * beyond this point!     *
/*------------------------*/


$_CW['settings']['mysql']['host'] = $MySQL_Host;
$_CW['settings']['mysql']['name'] = $MySQL_Name;
$_CW['settings']['mysql']['user'] = $MySQL_Username;
$_CW['settings']['mysql']['pass'] = $MySQL_Password;
unset($MySQL_Host,$MySQL_Name,$MySQL_Password,$MySQL_Username);


// gen securtity keys


?>
